### ISSUE TITLE
可以做到图层切换吗? 现在的情况只能先创建的在最下面一层

### ISSUE THREAD

**Issue by Bisond** [vincent111000/VCSticker#4]
可以做到图层切换吗? 现在的情况只能先创建的在最下面一层

**Comment by vincent111000** [comment]
这部分逻辑上层controller中可自行控制

**Comment by vincent111000** [comment]
[UIView exchangeSubviewAtIndex:indexA withSubviewAtIndex:indexB];

**Comment by vincent111000** [comment]
> 可以做到图层切换吗? 现在的情况只能先创建的在最下面一层

@Bisond 
[UIView exchangeSubviewAtIndex:indexA withSubviewAtIndex:indexB];
